### ISSUE TITLE
Display additional rotas

### ISSUE THREAD

**Issue by janipewter** [richardseabrook/samaritans-dashboard#1]
Hi all, first of all, great job with this, it is amazing! We are hopefully about to deploy this in the Plymouth branch imminently. We're just doing some tests first to get the screens set up nicely.

One thing we'd like to do is display extra rotas, for example our Duty Director rota and Priority Duty rota. We have given view access to our 'screen' user and have verified it can view these rotas. But they do not show on the dashboard.

**Comment by richardseabrook** [comment]
Hi Jani, great to hear of your project. The code here doesn't have anything to selectively show rotas (it shows everything it's given by 3R) so it sounds like it's not receiving these as you're expecting. Could it be that the API key entered into Balena is for a different user that has more restrictive permissions? Or perhaps 3R is blocking access to these rotas for another reason.

I would suggest double-checking the rota permissions and the API key in the first instance.

You can see the raw data that is being pulled from 3R within the branch by going to:

http://IP.ADDRESS.OF.NGINX/stats/export_rotas.json

Where IP.ADDRESS.OF.NGINX is substituted for the IP shown on the 'nginx' device page in Balena.

**Comment by janipewter** [comment]
Hi Richard, thanks for your reply. I checked today and it seems to be working, I can see Priority Duty on the rota and it shows in the json too.

**Comment by richardseabrook** [comment]
Glad it's OK. You will notice that rotas are only shown on a specific day if they have a rota 'slot' there (be it waiting for sign-up or filled) if there is no slot then it will not be shown as it is not exported in the feed from 3R.
