### ISSUE TITLE
balena-dash device just displays Balena logo

### ISSUE THREAD

**Issue by janipewter** [richardseabrook/samaritans-dashboard#2]
As above. I've done everything per the instructions and can see no reason why it's not working. I can access the nginx device and see the Sams dashboard from my laptop, and the balena-dash device can ping it fine. But it sits on the Balena logo no matter what. The console log in the balena dashboard doesn't give any useful information.

``` kiosk  Running balena base image entrypoint...
 kiosk  setting xserver-xorg-legacy/xwrapper/allowed_users from configuration file
 kiosk  Using default chromium flags
 kiosk  Disabling GPU acceleration
 kiosk  Adding user settings directory
 kiosk  Using fullscreen: 1920,1080
 kiosk  Enabling kiosk mode
 kiosk  Disabling cursor
 kiosk  2021/11/01 21:38:57 Command is '/home/chromium/launch.sh'
 kiosk  2021/11/01 21:38:57 Starting listening on port 8080
 kiosk  2021/11/01 21:38:57 Launch page with desiredURL = 'http://192.168.10.62'. Slack: false
 kiosk  2021/11/01 21:38:57 Redirecting to home page
 kiosk  2021/11/01 21:38:57 Running '/home/chromium/launch.sh http://192.168.10.62'
 kiosk  2021/11/01 21:38:57 Responded with home page
```

I tried setting the launch URL to google.com and that also didn't work. I can see it doesn't even try to do a DNS lookup. Any ideas of what I've done wrong? I'm using Pi 4B 4GB for everything.

**Comment by richardseabrook** [comment]
Hi, it looks like you might be affected by this issue:
https://github.com/balenalabs/balena-dash/issues/139

A fix seems to have been applied and if you update, this may resolve the problem.

**Comment by zdover** [comment]
Thanks for the heads-up. 

Kind regards,

Zach




1 Nov 2021, 22:36 by ***@***.***:

**Comment by janipewter** [comment]
Thanks, all sorted. Now just need to get the screens up on the walls in our branch :)
