### ISSUE TITLE
Reduce API request frequency

### ISSUE THREAD

**Issue by janipewter** [richardseabrook/samaritans-dashboard#3]
Can anyone point me to where in the code the API polling frequency is set? Samaritans central IT are upset that we are hitting the API every minute as it produces a lot of logs. I'd be happy with a 5 or even 15 minute update rate. I've had a glance at the JS but I am by no means a Javascript person and couldn't really figure it out.

Thanks
Jani

**Comment by richardseabrook** [comment]
Hi @janipewter,

You can find the refresh frequency in the code here:

https://github.com/richardseabrook/samaritans-dashboard/blob/bca5d6ca3df463c559d9ae664ca5f0bc1da788ae/html/index.html#L152

Thanks,
Richard

**Comment by janipewter** [comment]
Ah yes thank you, and thanks for replying so fast. I didn't even think of looking in the index.html, I was looking through the Javascript.

Cheers
Jani

**Comment by richardseabrook** [comment]
No problem 😃
