### ISSUE TITLE
Service status not loading

### ISSUE THREAD

**Issue by janipewter** [richardseabrook/samaritans-dashboard#4]
Not sure if anyone else is having this issue but I was informed by one of our volunteers that the service status (shown on the right-hand side of the dashboard) was not working.

After much digging I *think* I have narrowed the issue down to the fact that the service status webpage at https://dashboard.samaritans.org/intranet/status/ is sending the `X-Frame-Options: DENY` header which is being proxied through the dashboard page.

I've managed to fix it with this commit: https://github.com/janipewter/samaritans-dashboard/commit/19267ced4f7876c8fb5ebd882642b78859e2a75e

I'm not sure if both options are needed; I suspect only the first one is, but I couldn't be bothered testing.

**Comment by richardseabrook** [comment]
Many thanks for taking the time to do this @janipewter - I've pulled your commit into this project.
